export { default as WalkOnsBanner } from './banners/Walkons'
export { default as MercuryBanner } from './banners/Mercury'
export { default as OttoBanner } from './banners/Otto'
export { default as HomeNetworkBanner } from './banners/HomeNetwork'
export { default as CarputerBanner } from './banners/Carputer'
